name: Publish Love Drawing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Matplotlib (for drawing the heart shape)
      run: |
        pip install matplotlib

    - name: Run Python Script to Create Heart Drawing
      run: |
        python main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: love-drawing
        path: images/love_drawing.png
