name: Publish Turtle Script

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Optional, only if you have dependencies

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Run Turtle Script
        run: |
          python main.py

      - name: Convert EPS to PNG
        run: |
          convert love_drawing.eps love_drawing.png

      - name: Upload PNG as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: love-drawing
          path: love_drawing.png
